name: Build image

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set SERVER_IP, IMAGE_TAG and SERVICE_NAME
      run: |
        echo "SERVER_IP=$(curl -s https://config.isporit.com/ip)" >> $GITHUB_ENV
        echo "IMAGE_TAG=latest" >> $GITHUB_ENV 
        echo "SERVICE_NAME=prod_isporit_website" >> $GITHUB_ENV
    
    - name: Build docker images using cache
      uses: whoan/docker-build-with-cache-action@v5
      with:
        # Name of the image to build
        image_name: isporit-website
        image_tag: ${{env.IMAGE_TAG}}
        username: isporit
        password: ${{secrets.ISPORIT_ORG_TOKEN}} 
        registry: ghcr.io 
        
    - name: Deploy to swarm
      run: |
        eval $(ssh-agent -s)
        mkdir -m 0700 -p ~/.ssh/
        ssh-keyscan ${{env.SERVER_IP}} >> ~/.ssh/known_hosts
        ssh-add - <<< "$SSH_PRIVATE_KEY"
        docker --host "ssh://root@${{env.SERVER_IP}}" \
          service update --force --image ghcr.io/isporit/isporit-website:${{env.IMAGE_TAG}} ${{env.SERVICE_NAME}}
      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        
#     - uses: danielr1996/kubectl-action@1.0.0
#       name: Deploy
#       with:
#           kubeconfig: ${{ SECRETS.KUBE_CONFIG_DATA }}
#           args: rollout restart deployment/website-isporit -n website-isporit

