name: Build image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker images using cache
      uses: whoan/docker-build-with-cache-action@v5
      with:
        # Name of the image to build
        image_name: isporit-website
        username: someone
        password: ${{secrets.GITHUB_TOKEN}} 
        registry: docker.pkg.github.com 
    - uses: danielr1996/kubectl-action@1.0.0
      name: Deploy
      with:
          kubeconfig: ${{ SECRETS.KUBE_CONFIG_DATA }}
          args: rollout restart deployment/website-isporit -n website-isporit

