name: Build image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker images using cache
      uses: whoan/docker-build-with-cache-action@v5
      with:
        # Name of the image to build
        image_name: isporit-website
        username: someone
        password: ${{secrets.GITHUB_TOKEN}} 
        registry: docker.pkg.github.com 
    - name: Kubernetes CLI - kubectl
      uses: steebchen/kubectl@v1.0.0
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "1.18"
      with:
        args: '"rollout restart deployment/isporit-website -n isporit"'

